[package]
name = "line-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
env_logger = "0.10.0"
log = "0.4.17"
unicode-segmentation = "1.10.0"
